allowBuilds:
  msw: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@supabase/cli-darwin-arm64@2.105.0'
  - '@supabase/cli-darwin-x64@2.105.0'
  - '@supabase/cli-linux-arm64-musl@2.105.0'
  - '@supabase/cli-linux-arm64@2.105.0'
  - '@supabase/cli-linux-x64-musl@2.105.0'
  - '@supabase/cli-linux-x64@2.105.0'
  - '@supabase/cli-windows-arm64@2.105.0'
  - '@supabase/cli-windows-x64@2.105.0'
  - supabase@2.105.0
